### ISSUE TITLE
Multiple classes

### ISSUE THREAD

**Issue by dom-kelly** [GitScrum/postcss-attribute-selector-prefix#168]
Are multiple classes supported? e.g.

```
/* input.css */
.class, 
[type="text"], 
[class*="lorem-1 lorem-2"],
[id^="myID"] { 
    color: red; 
}

```

```
/* Output example */
.class, 
[type="text"], 
[class*="test-lorem-1, test-lorem-2"],
[id^="test-myID"] { 
    color: red; 
}
```

**Comment by Scrum** [comment]
@dominicjameskelly hi, not yet, but soon will be. Thanks for the feedback.

**Comment by dom-kelly** [comment]
Excellent, thanks!

**Comment by Scrum** [comment]
@dominicjameskelly Enjoy :)

**Comment by dom-kelly** [comment]
Thanks so much! I'll give it a go :)

**Comment by dom-kelly** [comment]
Trying to grab this from npm:

`npm install postcss-attribute-selector-prefix --save-dev
`

But it's fetching postcss-attribute-selector-prefix@0.0.12 which doesn't seem to include the changes in GIT?

**Comment by dom-kelly** [comment]
Ignore, got it pulled in fine now.

**Comment by Scrum** [comment]
👍

**Comment by dom-kelly** [comment]
Thanks again!
